<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">
  <meta name="Description" content=" [wstaw tu opis strony] ">
  <meta name="Keywords" content=" [wstaw tu slowa kluczowe] ">
  <meta name="Author" content=" [dane autora] ">
  <meta name="Generator" content="kED2">

  <title> Wyrski Serwis Pielgrzymkowy - Pielgrzymka Wyry-Częstochowa </title>

  <link rel="stylesheet" href=" style.css " type="text/css">
</head>
<body>

	<div class="top_menu">
		<div class="links">
		<?php include('menu_top.php'); ?>
			
		</div>
	</div> 
	<div class="logo"><img src="logo.png" /></div>
	<div class="content">
		<div class="menu">
			<div class="menu_top">
				<div>Menu</div>
			</div>			
			<?php include('menu_left.php'); ?>
			
		</div>
		<div class="text">
			<div class="header">
				<div>Pielgrzymka 2007 - Reportaż</div>
			</div>
			
			<div class="p">

					Już po raz piętnasty pielgrzymi z Wyr podjęli trzydniowy trud drogi, aby na Jasnej Górze przeżyć niesamowite spotkanie z Matką ludzkich serc - Królową Polski. Jednak zanim wyruszyliśmy czekało nas bardzo Ważne Spotkanie - Uczta Miłości. Była to wyjątkowa Uczta, gdzie podczas Jej trwania mogliśmy namacalnie doświadczyć obecności samego Jezusa Chrystusa, nie szukając Go daleko. Po tym wyjątkowym myślę, że dla każdego z nas wydarzeniu, przeszliśmy do strony organizacyjnej pielgrzymki. Każdy uczestnik otrzymał z rąk Mazika identyfikator oraz śpiewnik- niezbędny towarzysz przy bardzo częstej modlitwie śpiewem podczas drogi. Po "stronie organizacyjnej" przyszedł czas na "stronę duchową". Ksiądz proboszcz udzielił nam Bożego Błogosławieństwa, równocześnie życząc nam bezpiecznej drogi do celu. Wychodząc z Kościoła ks. Aleksander w bardzo znamienity sposób pożegnał nas - obficie kropiąc nas wodą święconą, co stało się już niemalże rok roczną tradycją pielgrzymkową. I wyruszyliśmy... <br><br />
Dnia 21 sierpnia ok. godz. 8:00 ze śpiewem na ustach i radością w sercu powoli udaliśmy się do naszego pierwszego postoju znajdującego się w Rudzie Śląskiej Bykowinie. W czasie drogi nie mogło zabraknąć szczególnej modlitwy, jaką jest różaniec. Rozważając jego tajemnice za wstawiennictwem Naszej Matki, zanosiliśmy nasze pielgrzymkowe intencje do Boga. Oczywiście nie mogłabym nie wspomnieć o śpiewie, który towarzyszył nam przez cały czas pielgrzymki. Ania Ania i Mazik jako muzyczni zagrzewali nas do śpiewu i nie pozwolili, abyśmy podczas drogi choć przez chwilę się  nudzili. Można powiedzieć, że modliliśmy się niemalże non - stop, śpiewając pieśni uwielbieniowe. Jak mówi stara piosenka: "Śpiewać każdy może", więc jeśli były nawet osoby, które fałszowały (ja osobiście nie słyszałam :P), ich sposób śpiewania jeszcze bardziej potęgował moc modlitwy:). Kiedy dotarliśmy do upragnionego postoju wiele osób odetchnęło z ulgą. Na miejscu czekali na nas p. Stasiu i prezes z ekipą, którzy przygotowali dla nas gorącą
herbatę i kawę, abyśmy mogli pokrzepić ciała do dalszego wędrowania. Jedni rzucili się na jedzenie, inni na trawę, a jeszcze inni do toalety:)). Delektowaliśmy się wolnym czasem aż do momentu, gdy wybiła godzina "0" (czytaj: ok. godz. 12:00), kiedy to udaliśmy się do Kościoła, bym tam odmówić "Anioł Pański" i prosić Jezusa o potrzebne nam łaski do dalszego pielgrzymowania. Czas ruszać! Najlepszym tzw. "pobudzaczem" była dla nas piosenka: "Pan mnie strzeże". Stała się ona nieoficjalnym hymnem pielgrzymkowym, bo była ona jedną z najbardziej lubianych przez nas piosenek. Kolejne kilometry do pokonania... i do wyczekiwanego postoju:) Dotarliśmy...(<owacje na stojąco>, ale najlepsze dopiero przed nami:) Tym razem Bytom czekał na nas można powiedzieć, że z otwartymi ramionami. Godzina 14:00 i wreszcie Kościół, jedzenie, toaleta, trawa, ciepły napój... Ok. godz. 15:00 udaliśmy się do pobliskiego Kościoła, aby tam w modlitwie zjednoczyć się z Jezusem w Jego nieskończonym Bożym Miłosierdziu i dosłownie stanąć
"twarzą w twarz" z kilometrami prowadzącymi do Piekar Śląskich, bo tam oprócz p. Stanisława, Prezesa i jego ekipy czekała na nas Matka Piekarska nasza Wspaniała Opiekunka, nasz najlepszy Przyjaciel Jezus i Umiłowany Ojciec Bóg. Oprócz tych Bliskich naszemu sercu Osobistości czekały na nas przyparafialne salki i prysznice. A droga jak na złość dłużyła się i dłużyła, czasem dając nam do odczucia wrażenie jej nieskończoności. Jednak za sprawą naszych niezastąpionych fankowych i osób, które niosły krzyż stopniowo zwiększaliśmy tempo, dzięki czemu w niedługim czasie bezpiecznie dotarliśmy do upragnionej przez nas Bazyliki Matki Piekarskiej. Gdy doszliśmy na miejsce (niektórzy się czołgali:P), w podziękowaniu za nieustanną Opiekę Matki Bożej podczas wędrówki oddaliśmy pokłon Matce Piekarskiej, a następnie udaliśmy się do salek, aby tam rozpakować nasze bagaże i przygotować miejsce do spania. I tu rozpoczął się prawdziwy Wyścig dosłownie przez duże "W". A nagrodą była... kąpiel pod prysznicem.
Wyścig odbywał się na zasadzie: "Kto pierwszy ten lepszy i...ma szczęście". Niestety wiele pielgrzymów nie dotarło na czas i niektórzy musieli czekać na swoją kąpiel ponad 2h, gdyż tego dnia zapomniano powołać służbę porządkową zajmującą się prysznicami, jednak nastąpiła szybka rehabilitacja i następnego dnia naprawiono ten błąd o czym dowiecie się w dalszej części tekstu:) W między czasie chętni mogli zasmakować rarytasów pielgrzymkowej kuchni czyli śląskich wusztów a'la Pan Stasiu & Prezes (niebo w gębie:)) i poleniuchować na karimatach. Cała służba pielgrzymkowa zadbała w szczegółach o stronę rozrywkową pielgrzymki.  Nie mogło zabraknąć słynnej zabawy "pif -paf", a także śpiewów na rozruszanie obolałych nóg z dużą ilością odcisków. Po czasie "Coś dla ciała" przyszedł czas na "Coś dla ducha". Ksiądz Krystian zadbał o to, abyśmy się zbytnio nie rozbrykali i podczas modlitwy wieczornej wyciszyli nasze serca i uzmysłowili sobie po co i dla Kogo, tak naprawdę podążamy do Częstochowy.
Następnie uroczyście odśpiewaliśmy "Apel Jasnogórski" i udaliśmy się do salek, aby pójść "spać". W rzeczywistości kto spał, ten spał:) Gdzie niegdzie na korytarzach i salkach słychać było szepty rozmów, a ci, którzy mieli jeszcze ogromne pokłady energii z księdzem na czele spożytkowali ją na grę w siatkówkę... I zanim wszyscy zasnęli minęło trochę czasu. A w nocy działy się różne rzeczy... Jedni gadali przez sen i można było dowiedzieć się wielu bardzo ciekawych rzeczy, inni nie mogli zasnąć i wiercili się z boku na bok, a w niektórych pokojach było słychać donośne chrapanie...Jednak te informacje nie pobiją wstrząsającego newsa, który za chwilę opiszę... Jak donosi Agencja Informacyjna Wyrskiej Pielgrzymki jeden z naszych dzielnych fankowych w nocy z wtorku na środę (21/22 sierpnia) uległ wypadkowi, z którego uszedł cudem. Nasz fankowy po ciemku próbował wejść na pakę samochodu przewożącego bagaże pielgrzymów (jeszcze nie zostało ustalone w jakim celu), a gdy mu się to udało,
niestety nie zauważył paska zabezpieczającego naczepę, potknął się o niego i wylądował...z wyciągniętymi rękoma w garnku z wusztami... Być może miał zamiar zaspokoić swój głód, a że miał do tego świetne "okoliczności sprzyjające" i jak głosi jedno z porzekadeł: "Mówisz i masz" (w tym przypadku można by raczej użyć stwierdzenia: "Mówisz, leeeecisz i masz") - zaspokoił swoje pragnienie niemal natychmiastowo. Fankowy uszedł z życiem, ale to wydarzenie pozostanie w nim jeszcze na dłuuugo. I tak minął dzień pierwszy naszego pielgrzymowania. <br><br />
Nastał poranek, dzień drugi (22 sierpień). Poranna toaleta, Msza Święta - przepiękna zarówno w treści jak i przekazie  (nie mogę nie wspomnieć o oryginalnym wykonaniu psalmu przez dwie dziewczyny - niestety nie pamiętam imion:P), smaczne śniadanko...no i ruszamy w drogę! Misją dnia było pokonanie 30 km i dojście do Szkoły Podstawowej w Woźnikach. Nie zdążyłam jeszcze wspomnieć o naszych tubiarzach (Adam i Sławek znany też jako "Mody"), którzy dzielnie maszerowali ze sprzętem na plecach, dbając o to, aby było nas jak najlepiej słychać....czasami było nawet bardzo głośno. Idziemy, idziemy i wydaje się, że znów końca nie widać....Oczywiście nie zawsze jest pięknie, lekko i przyjemnie i jak to czasami na szlaku bywa dzieją się różne rzeczy, a raczej ludzie odnoszą kontuzje i tak było tym razem...Jednak wystarczył jeden telefon i nasz niezastąpiony prezes niczym "Superman"  pojawiał się szybko, zabierał kontuzjowanych pielgrzymów i...równie szybko znikał, czekając z kontuzjowanymi na postoju.
A my dreptaliśmy z nadzieją dotrwania do następnego postoju i aby zapomnieć o zmęczonych mięśniach, zblazowanych nogach i obolałych kościach nasi muzyczni bardzo skutecznie pozwalali zajmować nam myśli i sprawiali, że chociaż na chwilę zapominaliśmy o naszych fizycznych niedomaganiach oraz poprawiali humor, gdy było już naprawdę ciężko. I wreszcie postój...Miasteczko Śląskie. Posilenie się jedzonkiem i w drogę, ale nie tak szybko...:) Tradycyjnie "Anioł Pański" w przeuroczym kościółku i do roboty:) Podczas drogi działy się różne rzeczy:) Ci, którzy mieli już naprawdę dość, wszystko ich bolało i mieli najczarniejsze myśli w głowie skutecznie prostował ks. Krystian zdaniami: "Jeżeli Cię boli to znaczy, że żyjesz" lub "Nie świruj, bo dasz radę" i to naprawdę mobilizowało:)Ks. Krystian udowodnił po raz kolejny, że ma ogromny dar przekonywania i wie jak przemówić do rozsądku:). Jak to mówią "w kupie siła" i rzeczywiście była, bo każdy kto gorzej się czuł mógł liczyć na sąsiada obok, mógł się wyżalić
albo porozmawiać... i takie rozmowy sprawiały, że stawaliśmy się sobie bliżsi, przez co nabieraliśmy do siebie coraz większego zaufania, a to wszystko za sprawą działania Pana Jezusa, bo to On prawdziwie jednoczy ludzi, sprawia, że czasem rozumieją się bez słów... Wystarczy przy kimś być, by wiedzieć i czuć, że działa przez nas sam Bóg...Działa Jego Miłość, która czyni cuda, ulecza, oczyszcza...Powróćmy jednak do pielgrzymkowej rzeczywistości:) Kolejny postój to las;) chyba nie muszę powtarzać co przeważnie robi się na postojach:), bo czytając ten tekst można wykuć to na pamięć...Trawa... itp. itd.:) I ruszamy...Cały czas ciągnie się las i las i las i las...niektórzy stracili poczucie rzeczywistości i czuli się w nim niczym w tropikalnych lasach deszczowych. Po drodze spotkaliśmy krowy, które na nasz widok wydały z siebie radosne "muuu" oraz inne, mniejsze lub większe zwierzęta. Po tylu godzinach maszerowania widzi się różne rzeczy:P A gdy skończył się las wszyscy odetchnęli z ulgą i tak bardzo
pragnęliśmy jak najszybciej dostać się do szkoły, że krzyż "nieco" przyspieszył, co doprowadziło do chwilowych zamieszek, ponieważ niektórzy nie nadążali. Jednak sytuacja została szybko opanowana. Dotarliśmy do Kościoła, niektórzy z uśmiechem na twarzy, inni ze łzami w oczach, a jeszcze inni z grymasem wywołanym zapewne wszechstronnym bólem. Podziękowaliśmy Jezusowi za szczęśliwe dotarcie do kolejnego celu i prosiliśmy o nieskończone pokłady sił na następny dzień - dzień szczególny spotkania z Matką na Jasnej Górze, dlatego potrzebowaliśmy ogromnej pomocy Boga, bo bez Niego nie dalibyśmy rady dojść nawet do Rudy Śląskiej. Szkoła...Nareszcie i znów walka o miejsce w kolejce pod prysznic...Jednak tak jak wspomniałam wcześniej szybko naprawiano błąd związany z brakiem służby porządkowej do łazienki. Tym razem w roli strażnika czasu i miłości do bliźniego wystąpiła Amela - sama zgłosiła się do tego zadania, bez żadnych głosów ze strony ludu, podjęła wręcz ekstremalne zadanie zmierzenia się z 94 osobami,
które w 5 min. miały błyskawicznie się umyć i w tym samym czasie być ubranym. Z pozoru łagodna i niewinna Amela przekształciła się w prawdziwego strażnika, a gdy ktoś siedział o 1 sek. za długo groziła wyciągnięciem z pod prysznica:) Kąpiel pod presją okazała się zbawienna. Wszyscy wzięli sobie te słowa do serca i pilnowali swojego czasu, przez co kąpiel trwała bardzo szybko i nie było z nią problemów. W między czasie przyjechał ks. Proboszcz - sprawdził czy wszystko w porządku i czy wszyscy przeżyli oraz przywiózł nam małą niespodziankę - ciasto z kruszonką, które miało służyć nam jako posilenie przed najtrudniejszym, a zarazem najpiękniejszym dniem pielgrzymki. Gdy wszyscy się wykąpali czekał na nas kolejny wieczór z serii: "Coś dla ciała i ducha". Pogodny wieczór rozpoczęliśmy uwielbieniowym tańcem, później "zrobiliśmy z siebie" węzły, które trzeba było rozplątać na różniste sposoby, zabawa ta wymagała też odrobiny logicznego myślenia i towarzyszyła nam przy niej duża ilość śmiechu, a potem tworzyliśmy
zamki i szukaliśmy księżniczek. Radości było co nie miara, co było widać po rozpromienionych twarzach pielgrzymów. Naszą radość zwieńczyliśmy przepiękną modlitwą "Koronką do Aniołów Stróżów", którą odmówiliśmy na zakończenie burzliwego dnia:). A potem rozeszliśmy się do klas - nie ma to jak spać w szkole, kiedy wakacje powoli się kończą, a nam wcale nie spieszno do szkoły:P. To była bardzo długa noc - przynajmniej dla mnie. Na początku przez większą część jej trwania wierciłam się, bo było mi strasznie niewygodnie i bardzo odczuwałam fakt, że śpię na podłodze. Jednak Pan Jezus nie pozwolił na to, abym zbytnio się zmęczyła i nawet nie pamiętam, kiedy zasnęłam. Nie wiem jakim cudem wstałam rano po tych wydawałoby się dla niektórych "traumatycznych" przeżyciach, ale dałam radę i to najbardziej motywowało mnie do dalszego pielgrzymowania.<br><br />
I tak nastał dzień trzeci (23 sierpień) - ostatni dzień wędrówki... Na dobre rozpoczęcie dnia  słowa księdza Krystiana: "Tak jak my gadali" - powiedziały mi z Justyną wszystko:) Czeka nas do zaśpiewania psalm na Mszy:), więc "prędko" do Kościoła, aby go przećwiczyć. Jednak to nasze prędko wcale nie wyglądało na szybkie tempo za sprawą odcisków na palcach Justyny i moich obolałych nóg, ale szczęśliwie doszłyśmy mieszcząc się w czasie i spotkałyśmy się z ogromną życzliwością kościelnego. Jak wyszedł nasz psalm pozostawiamy już waszemu zdaniu drodzy pielgrzymi, ale kilka śmiesznych momentów było:). Msza była piękna - na kazaniu ksiądz Krystian mówił o uczcie weselnej, a dokładniej o przywdzianiu szat weselnych podczas spotkania z Maryją. Każdy z nas zadawał sobie pytanie: Czy jestem godny przywdziania owych szat?, czy zasługuję na uczestnictwo w takiej Uczcie?, czy biel szat weselnych jest odzwierciedleniem stanu, w którym obecnie znajduje się moje serce? Myślę, że kazanie dało bardzo do myślenia,
ukazało wiele ważnych spraw, nad którymi zbyt mało myśleliśmy lub wcale się nie zastanawialiśmy. Uświadomiło jak jeszcze wiele musimy zmienić w naszych życiu i że owe zmiany są niezbędne do Prawdziwego Życia w WOLNOŚCI, do Prawdziwego Życia przez Chrystusa, z Chrystusem i w Chrystusie. A po Mszy szybkie śniadanko i w drogę...:) Tylko 30 i aż 30 kilometrów dzieliło nas od Naszej Ukochanej Matki...Jednak Wyry tak łatwo się nie poddają i walczą z kilometrami, z niemiłosiernym upałem, który nie dał o sobie zapomnieć i towarzyszył nam przez cały dzień. Również tego dnia otrzymaliśmy żółto - niebieskie koszulki, które zostały specjalnie zrobione na tę okazję. A na nich piękne logo i nasz oficjalny hymn pielgrzymki (jego treść znajduje się pod nagłówkiem tekstu), który nieustannie towarzyszył nam tego dnia w wędrowaniu:) Podczas marszu wybieraliśmy najlepsze hity pielgrzymkowe - najlepsza piosenka miała zostać zaprezentowana podczas uroczystego wejścia na Jasną Górę :)
A w roli DJ'ÓW wystąpili nasi niezawodni muzyczni oraz Ruby służący za mikser:) Trwała zacięta walka pomiędzy utworami "Wyry kochają...", "Pan mnie strzeże" oraz "Panie Ty jesteś radością mą". Niestety nie potrafię sobie przypomnieć, który utwór zdobył największą sympatię pielgrzymów, ale sądząc po entuzjazmie, z jakim śpiewaliśmy owe piosenki sądzę, że najbardziej przypadła nam do gustu piosenka: "Pan mnie strzeże". Ostatni postój i najcięższy, ale zarazem najpiękniejszy odcinek drogi. Fankowi zawsze w pogotowiu, czuwali nad naszym bezpieczeństwem i z uwagą śledzili ruch drogowy na trasie wjazdowej do Częstochowy. Śpiew pomagał i podnosił, ksiądz motywował, tubiarz czuwał nad nagłośnieniem, krzyż nad tempem marszu, a my oczekiwaliśmy wejścia. I wreszcie przejazd kolejowy, który pozwalał zrozumieć jedno: Jesteśmy blisko, na wyciągnięcie ręki...Jeszcze tylko kawałek i będziemy mogli spotkać się naszą Ukochaną Mamą...W tym momencie uświadomiłam sobie jak wielką i ogromną radość przynosi mi
 myśl o tym bardzo ważnym dla mnie Spotkaniu, a jednocześnie wzruszenie i ociekające łzy po policzkach sprawiały, że czułam się jak dziecko, które przybiegło, aby usiąść na kolanach Swojej Mamy i pragnęło z całego serca bardzo mocno się w Nią wtulić:) Musieliśmy przejść jeszcze spory kawałek miasta, aby móc przejść przez mury Jasnej Góry. Dotarliśmy do jasnogórskiego parku od strony, którego wszystkie pielgrzymki uroczyście przekraczają próg Domu Matki Bożej. Podczas tego myślę, że dla wszystkich niezapomnianego momentu towarzyszył nam nasz wyrski hymn oraz niewypowiedziana radość w sercach, której naprawdę nie da się opisać słowami, trzeba samemu przekonać się o niej na własnej skórze - wierzę, że pielgrzymi na pewno w duchu zgadzają się z moimi słowami. Przekroczyliśmy mury Sanktuarium i stało się... Matka Boża czekała na nas z otwartymi ramionami. Od wejścia biła od Niej Ogromna Miłość....Po raz kolejny uświadomiła nam, że jesteśmy Jej ukochanymi dziećmi, przytuliła bardzo, bardzo mocno i
  jednocześnie bardzo zapragnęła, abyśmy już na zawsze pozostali w Jej objęciach...A później każdy w cichej kontemplacji, w swoim uniżeniu ofiarował jej swoje życie - problemy, zamierzenia, prośby, plany, marzenia - swoją codzienność. Po tym niezwykłym spotkaniu udaliśmy się do Domu Pielgrzyma - tam czekały na nas przytulne pokoje i wygodne łóżka. Już nie było wyścigu do pryszniców:) każdy kąpał się według swojej strefy czasowej:)...Po kąpieli część udała się na miasto w poszukiwaniu swojego obiadu, a raczej obiado - kolacji:), a część pielgrzymów oczekiwała na Apel Jasnogórski, który odbywał się w Kaplicy Najświętszego Obrazu i rozpoczął się o godz. 21:00. Natomiast po Apelu spotkała nas bardzo miła niespodzianka:) Podczas tradycyjnego spotkania organizacyjnego, które odbywało się w "oczku wodnym", przyłączyła się do nas Pielgrzymka Młodzieżowa z Rudy Śląskiej Halemby 1.Pielgrzymi z Rudy bardzo entuzjastycznie włączyli się do wspólnego świętowania:) Zabawa była przednia, nawet panowie ze Straży
  Miejskiej włączyli się do śpiewu robiąc przy tym niemałą furorę. Telewizja też nie przegapiła naszego świętowania i zarejestrowała nasze wyczyny:P (lepiej nie pytajcie jakie:P). <z tego co kojarze to był to kamerzysta tamtej pielgrzymki a nie TV, ale pewny nie jestem - elvis> Minęła 22:00 i niestety musieliśmy kończyć, ponieważ Dom Pielgrzyma zamykany jest właśnie o tej godzinie i na koniec odśpiewaliśmy krótką modlitwę wieczorną, a następnie udaliśmy się na spoczynek do swoich pokojów.<br><br />
Dzień IV (24 sierpień) rozpoczęliśmy wspólnotowym spotkaniem na Wałach z parafianami z Wyr, którzy przyjechali z naszej rodzinnej miejscowości, aby wspólnie z nami łączyć się we wspólnej modlitwie, rozważając stacje Drogi Krzyżowej. Tutaj przyszedł czas na refleksje... Czas na głębokie zamyślenie nad sobą i swoim życiem, czas na konkretne zmiany i zdecydowaną przemianę naszych serc. Po wspólnej modlitwie godzinka czasu wolnego na przygotowanie się do Mszy...:) Msza...Jak cudownie jest przeżywać każdą Mszę w inny sposób, odkrywać na nowo Boga, spotykając się z Nim w Jego Słowie, W Jego Ciele... Odczuwać Jego obecność i z całego serca cieszyć się nią...:) Po Mszy masa wolnego czasu przeznaczonego na zakupy i szukanie obiadu:), a następnie wspólny różaniec w kaplicy Matki Bożej Różańcowej...Chwila czasu, którą większa część osób przeznaczyła na krótką rozmowę z Mamusią.... i szukanie autobusów na parkingu. Ok. 17:00 wyjechaliśmy z Częstochowy i udaliśmy się do Wyr... i w tym momencie można by napisać: "Koniec". Ale nie tak szybko:) Czas trwania pielgrzymki osiągnął swój kres z chwilą wyśpiewania uroczystego "Te deum Laudamus", ale zanim to nastąpiło, miały miejsce serdeczne podziękowania dla wszystkich, którzy w jakikolwiek sposób włączyli się w organizację i prawidłowy przebieg pielgrzymki.
 <br><br>
Szczególne podziękowania za swój ogromny wkład pracy kierujemy do:
 <br><br>
fankowych - Krzysia, Radka i Klaudiusza - za bezpieczne dostarczenie nas na Jasną Górę <br>
muzycznych - Ani Ani i Adama (Mazika) za zagrzewanie nas do śpiewu i dopingowaniu nas w drodze
<br>tubiarzy - Adama i Sławka - za wytrwałość w noszeniu i dbanie o właściwe nagłośnienie <br>
służb medycznych - za każde ulżenie w bólu, za cierpliwość, za troskliwość podczas wykonywania    swojej służby  <br>
pielgrzymów noszących krzyż - za to, że dawali nam odpowiednie tempo i przypominali nam, że każdy z nas niesie krzyż swojej codzienności <br>
pielgrzymów uczestniczących w pieszej pielgrzymce - za odwagę i dawanie żywego świadectwa wiary podczas drogi  <br>
osób, które doprowadziły do powstania koszulek - za włożenie w nie dosłownie całego serca (czyli Pani Basi Mazur, Pani Basi Prasoł i innych parafian)<br>
pielgrzymów "autokarowych i samochodowych" - za to, że włączyli się w dzieło wspólnej modlitwy i wspierali nas modlitewnie podczas całego czasu trwania pielgrzymki <br>
Pana Krzysztofa, Prezesa i reszty świata - za to, że dbali o nasze bagaże i żołądki, oraz za pomoc w trudnych chwilach   <br>
Ks. Krystiana  - za wszelką pomoc duchową, za każdą spowiedź, wsparcie, modlitwę, dobre słowo, za to, że dbał o to, aby nikomu nic się nie stało i czuwał nad wszystkim:) Za każdą Mszę i każde kazanie, za wszelką dobroć, którą otrzymaliśmy od księdza  <br>
Osób, które w jakikolwiek sposób przyczynili się do zorganizowania tej pielgrzymki i modlili się o jej prawidłowy przebieg <br>
A najważniejsze podziękowania należą się Panu Bogu - za Ojcowską Opiekę i pomoc w każdej chwili, za to, że zawsze byłeś Tato  <br>
Jezusowi - za to, że był z nami przez ten cały czas i dawał nam się poznawać przez drugiego człowieka, za miłość, której mogliśmy tak bardzo doświadczać  <br>
Duchowi Świętemu - za to, że był naszym Duchowym Przewodnikiem, wskazywał właściwą drogę i prowadził nas do celu <br>
Maryi - za jej Matczyną Opiekę i wstawiennictwo w naszych sprawach, za to, że zawsze słuchałaś Mamo  <br>
Aniołowi Stróżowi - za szczególną opiekę i wierność swoim podopiecznym:)<br>
Wszystkim Świętym i Błogosławionym - za modlitwy i wstawiennictwo u Boga  <br>
</p>
 <br><br>


				 <br><br>KONIEC  <br>
				<B> Autor: Ania Danielczyk</B>


<br /><br />

			</div>
		</div>	
	</div>
	<div class="bottom">
		<div class="bottom_top">
			<div class="gray">
				<div class="gray_box"></div>
			</div>
		</div>
		
	<?php include('bottom.php'); ?>	
		
	</div>
	

</body>
</html>
